name: ZentiScan
options:
  bundleIdPrefix: no.zenti
  deploymentTarget:
    iOS: "16.0"
targets:
  ZentiScan:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "README.md"
          - "project.yml"
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        NSCameraUsageDescription: "Vi trenger tilgang til kameraet for å skanne QR-koder og utstyr"
    dependencies:
      - package: MSAL
packages:
  MSAL:
    url: https://github.com/AzureAD/microsoft-authentication-library-for-objc.git
    from: 1.3.0
